// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coddqwmvygarpjnagouu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZGRxd212eWdhcnBqbmFnb3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzg2NTUsImV4cCI6MjA1NjkxNDY1NX0.bVwuHDD0m5XA24-Q1wU_JY1TOYrQ2S_U3cRn7mSZa2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);